create extension if not exists "pgcrypto";

create table if not exists profile (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  title text not null,
  slogan text not null,
  email text not null,
  tags text[] not null default '{}',
  socials jsonb not null default '[]'::jsonb
);

create table if not exists news (
  id bigint generated by default as identity primary key,
  date text not null,
  emoji text not null,
  content text not null,
  sort_order integer
);

create table if not exists gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text not null,
  tag text not null,
  prompt text not null,
  sort_order integer
);

alter table profile enable row level security;
alter table news enable row level security;
alter table gallery enable row level security;

create policy "Public read" on profile for select using (true);
create policy "Public read" on news for select using (true);
create policy "Public read" on gallery for select using (true);
