create extension if not exists "pgcrypto";

create table if not exists profile (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  title text not null,
  slogan text not null,
  email text not null,
  tags text[] not null default '{}',
  socials jsonb not null default '[]'::jsonb,
  avatar_url text,
  show_gallery boolean not null default false
);

create table if not exists news (
  id bigint generated by default as identity primary key,
  date text not null,
  emoji text not null,
  content text not null,
  sort_order integer
);

create table if not exists gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text not null,
  tag text not null,
  prompt text not null,
  sort_order integer
);

alter table profile enable row level security;
alter table news enable row level security;
alter table gallery enable row level security;

create policy "Public read" on profile for select using (true);
create policy "Public read" on news for select using (true);
create policy "Public read" on gallery for select using (true);

alter table news add column if not exists title text;
alter table news add column if not exists summary text;
alter table news add column if not exists source text;
alter table news add column if not exists url text;
alter table news add column if not exists content_md text;
alter table news add column if not exists content_html text;
alter table news add column if not exists published_at timestamptz;
alter table news alter column content drop not null;
alter table news alter column content set default '';

create unique index if not exists news_url_key on news (url);
